//! Feature modules

pub mod batch;
pub mod drag_drop;
pub mod drag_out;
pub mod file_menu;
pub mod file_name_panel;
pub mod file_workspace;
pub mod folder;
pub mod folder_controls;
pub mod folder_workspace;
pub mod markers;
pub mod media_viewer;
pub mod recent_folders;
pub mod rotation_text;
pub mod settings;
pub mod sync_panel;
pub mod tag_grid;
pub mod tag_panel;
pub mod updates;
pub mod video_controls;
