//! Storage for the default set of stored tag names (built-in list).

/// Holds the default stored tag names. TagList is built from these names and a file's FileTags.
pub struct TagStorage;

impl TagStorage {
    /// Default set of stored tag names (order and labels for the tag list).
    pub const STORED_TAG_NAMES: &'static [&'static str] = &[
        "Action",
        "Adventure",
        "Animation",
        "Architecture",
        "Art",
        "Astronomy",
        "Biography",
        "Blog",
        "Business",
        "Celebration",
        "Classic",
        "Comedy",
        "Concert",
        "Cooking",
        "Dance",
        "Design",
        "Documentary",
        "Drama",
        "Education",
        "Entertainment",
        "Environment",
        "Event",
        "Experimental",
        "Family",
        "Fantasy",
        "Fashion",
        "Finance",
        "Fitness",
        "Food",
        "Gaming",
        "Gardening",
        "Geography",
        "Health",
        "History",
        "Holiday",
        "Home Improvement",
        "Horror",
        "How-To",
        "Humor",
        "Indie",
        "Industrial",
        "Interview",
        "Journalism",
        "Kids",
        "Landscape",
        "Language",
        "Lecture",
        "Lifestyle",
        "Literature",
        "Live Stream",
        "Mathematics",
        "Medicine",
        "Military",
        "Motivation",
        "Music",
        "Mystery",
        "Mythology",
        "Nature",
        "News",
        "Outdoors",
        "Parody",
        "Performance",
        "Pets",
        "Philosophy",
        "Photography",
        "Physics",
        "Podcast",
        "Politics",
        "Portrait",
        "Presentation",
        "Psychology",
        "Puzzle",
        "Reality",
        "Religion",
        "Retro",
        "Review",
        "Romance",
        "Satire",
        "Science",
        "Science Fiction",
        "Short Film",
        "Social Media",
        "Space",
        "Sports",
        "Suspense",
        "Technology",
        "Thriller",
        "Time-Lapse",
        "Travel",
        "Tutorial",
        "Underwater",
        "Urban",
        "Vlog",
        "Weather",
        "Wedding",
        "Western",
        "Wildlife",
        "Workout",
        "Workshop",
        "Yoga",
    ];

    /// Return the stored tag names slice.
    pub fn names() -> &'static [&'static str] {
        Self::STORED_TAG_NAMES
    }
}
